config/routes.rb
Rails.application.routes.draw do
  resources :david_and_naomis
  resources :cody_and_amandas
  resources :jjs
  resources :shorties
  resources :grams
  resources :tom_and_moms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tom_and_mom.rb
class TomAndMom < ApplicationRecord
end

app/controllers/tom_and_moms_controller.rb
class TomAndMomsController < ApplicationController
  before_action :set_tom_and_mom, only: [:show, :edit, :update, :destroy]

  # GET /tom_and_moms
  # GET /tom_and_moms.json
  def index
    @tom_and_moms = TomAndMom.all
  end

  # GET /tom_and_moms/1
  # GET /tom_and_moms/1.json
  def show
  end

  # GET /tom_and_moms/new
  def new
    @tom_and_mom = TomAndMom.new
  end

  # GET /tom_and_moms/1/edit
  def edit
  end

  # POST /tom_and_moms
  # POST /tom_and_moms.json
  def create
    @tom_and_mom = TomAndMom.new(tom_and_mom_params)

    respond_to do |format|
      if @tom_and_mom.save
        format.html { redirect_to @tom_and_mom, notice: 'Tom and mom was successfully created.' }
        format.json { render :show, status: :created, location: @tom_and_mom }
      else
        format.html { render :new }
        format.json { render json: @tom_and_mom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tom_and_moms/1
  # PATCH/PUT /tom_and_moms/1.json
  def update
    respond_to do |format|
      if @tom_and_mom.update(tom_and_mom_params)
        format.html { redirect_to @tom_and_mom, notice: 'Tom and mom was successfully updated.' }
        format.json { render :show, status: :ok, location: @tom_and_mom }
      else
        format.html { render :edit }
        format.json { render json: @tom_and_mom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tom_and_moms/1
  # DELETE /tom_and_moms/1.json
  def destroy
    @tom_and_mom.destroy
    respond_to do |format|
      format.html { redirect_to tom_and_moms_url, notice: 'Tom and mom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tom_and_mom
      @tom_and_mom = TomAndMom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tom_and_mom_params
      params.require(:tom_and_mom).permit(:header, :body)
    end
end

app/helpers/tom_and_moms_helper.rb
module TomAndMomsHelper
end

app/views/tom_and_moms/_form.html.erb
<%= form_with(model: tom_and_mom, local: true) do |form| %>
  <% if tom_and_mom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tom_and_mom.errors.count, "error") %> prohibited this tom_and_mom from being saved:</h2>

      <ul>
      <% tom_and_mom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :header %>
    <%= form.text_field :header, id: :tom_and_mom_header %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :tom_and_mom_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tom_and_moms/edit.html.erb
<h1>Editing Tom And Mom</h1>

<%= render 'form', tom_and_mom: @tom_and_mom %>

<%= link_to 'Show', @tom_and_mom %> |
<%= link_to 'Back', tom_and_moms_path %>

app/views/tom_and_moms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tom And Moms</h1>

<table>
  <thead>
    <tr>
      <th>Header</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tom_and_moms.each do |tom_and_mom| %>
      <tr>
        <td><%= tom_and_mom.header %></td>
        <td><%= tom_and_mom.body %></td>
        <td><%= link_to 'Show', tom_and_mom %></td>
        <td><%= link_to 'Edit', edit_tom_and_mom_path(tom_and_mom) %></td>
        <td><%= link_to 'Destroy', tom_and_mom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tom And Mom', new_tom_and_mom_path %>

app/views/tom_and_moms/new.html.erb
<h1>New Tom And Mom</h1>

<%= render 'form', tom_and_mom: @tom_and_mom %>

<%= link_to 'Back', tom_and_moms_path %>

app/views/tom_and_moms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Header:</strong>
  <%= @tom_and_mom.header %>
</p>

<p>
  <strong>Body:</strong>
  <%= @tom_and_mom.body %>
</p>

<%= link_to 'Edit', edit_tom_and_mom_path(@tom_and_mom) %> |
<%= link_to 'Back', tom_and_moms_path %>