config/routes.rb
Rails.application.routes.draw do
  resources :david_and_naomis
  resources :cody_and_amandas
  resources :jjs
  resources :shorties
  resources :grams
  resources :tom_and_moms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cody_and_amanda.rb
class CodyAndAmanda < ApplicationRecord
end

app/controllers/cody_and_amandas_controller.rb
class CodyAndAmandasController < ApplicationController
  before_action :set_cody_and_amanda, only: [:show, :edit, :update, :destroy]

  # GET /cody_and_amandas
  # GET /cody_and_amandas.json
  def index
    @cody_and_amandas = CodyAndAmanda.all
  end

  # GET /cody_and_amandas/1
  # GET /cody_and_amandas/1.json
  def show
  end

  # GET /cody_and_amandas/new
  def new
    @cody_and_amanda = CodyAndAmanda.new
  end

  # GET /cody_and_amandas/1/edit
  def edit
  end

  # POST /cody_and_amandas
  # POST /cody_and_amandas.json
  def create
    @cody_and_amanda = CodyAndAmanda.new(cody_and_amanda_params)

    respond_to do |format|
      if @cody_and_amanda.save
        format.html { redirect_to @cody_and_amanda, notice: 'Cody and amanda was successfully created.' }
        format.json { render :show, status: :created, location: @cody_and_amanda }
      else
        format.html { render :new }
        format.json { render json: @cody_and_amanda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cody_and_amandas/1
  # PATCH/PUT /cody_and_amandas/1.json
  def update
    respond_to do |format|
      if @cody_and_amanda.update(cody_and_amanda_params)
        format.html { redirect_to @cody_and_amanda, notice: 'Cody and amanda was successfully updated.' }
        format.json { render :show, status: :ok, location: @cody_and_amanda }
      else
        format.html { render :edit }
        format.json { render json: @cody_and_amanda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cody_and_amandas/1
  # DELETE /cody_and_amandas/1.json
  def destroy
    @cody_and_amanda.destroy
    respond_to do |format|
      format.html { redirect_to cody_and_amandas_url, notice: 'Cody and amanda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cody_and_amanda
      @cody_and_amanda = CodyAndAmanda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cody_and_amanda_params
      params.require(:cody_and_amanda).permit(:header, :body)
    end
end

app/helpers/cody_and_amandas_helper.rb
module CodyAndAmandasHelper
end

app/views/cody_and_amandas/_form.html.erb
<%= form_with(model: cody_and_amanda, local: true) do |form| %>
  <% if cody_and_amanda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cody_and_amanda.errors.count, "error") %> prohibited this cody_and_amanda from being saved:</h2>

      <ul>
      <% cody_and_amanda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :header %>
    <%= form.text_field :header, id: :cody_and_amanda_header %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :cody_and_amanda_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cody_and_amandas/edit.html.erb
<h1>Editing Cody And Amanda</h1>

<%= render 'form', cody_and_amanda: @cody_and_amanda %>

<%= link_to 'Show', @cody_and_amanda %> |
<%= link_to 'Back', cody_and_amandas_path %>

app/views/cody_and_amandas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cody And Amandas</h1>

<table>
  <thead>
    <tr>
      <th>Header</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cody_and_amandas.each do |cody_and_amanda| %>
      <tr>
        <td><%= cody_and_amanda.header %></td>
        <td><%= cody_and_amanda.body %></td>
        <td><%= link_to 'Show', cody_and_amanda %></td>
        <td><%= link_to 'Edit', edit_cody_and_amanda_path(cody_and_amanda) %></td>
        <td><%= link_to 'Destroy', cody_and_amanda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cody And Amanda', new_cody_and_amanda_path %>

app/views/cody_and_amandas/new.html.erb
<h1>New Cody And Amanda</h1>

<%= render 'form', cody_and_amanda: @cody_and_amanda %>

<%= link_to 'Back', cody_and_amandas_path %>

app/views/cody_and_amandas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Header:</strong>
  <%= @cody_and_amanda.header %>
</p>

<p>
  <strong>Body:</strong>
  <%= @cody_and_amanda.body %>
</p>

<%= link_to 'Edit', edit_cody_and_amanda_path(@cody_and_amanda) %> |
<%= link_to 'Back', cody_and_amandas_path %>