config/routes.rb
Rails.application.routes.draw do
  resources :david_and_naomis
  resources :cody_and_amandas
  resources :jjs
  resources :shorties
  resources :grams
  resources :tom_and_moms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/jj.rb
class Jj < ApplicationRecord
end

app/controllers/j_js_controller.rb
class JJsController < ApplicationController
  before_action :set_jj, only: [:show, :edit, :update, :destroy]

  # GET /jjs
  # GET /jjs.json
  def index
    @jjs = Jj.all
  end

  # GET /jjs/1
  # GET /jjs/1.json
  def show
  end

  # GET /jjs/new
  def new
    @jj = Jj.new
  end

  # GET /jjs/1/edit
  def edit
  end

  # POST /jjs
  # POST /jjs.json
  def create
    @jj = Jj.new(jj_params)

    respond_to do |format|
      if @jj.save
        format.html { redirect_to @jj, notice: 'Jj was successfully created.' }
        format.json { render :show, status: :created, location: @jj }
      else
        format.html { render :new }
        format.json { render json: @jj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jjs/1
  # PATCH/PUT /jjs/1.json
  def update
    respond_to do |format|
      if @jj.update(jj_params)
        format.html { redirect_to @jj, notice: 'Jj was successfully updated.' }
        format.json { render :show, status: :ok, location: @jj }
      else
        format.html { render :edit }
        format.json { render json: @jj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jjs/1
  # DELETE /jjs/1.json
  def destroy
    @jj.destroy
    respond_to do |format|
      format.html { redirect_to jjs_url, notice: 'Jj was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jj
      @jj = Jj.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jj_params
      params.require(:jj).permit(:header, :body)
    end
end

app/helpers/j_js_helper.rb
module JJsHelper
end

app/views/j_js/_form.html.erb
<%= form_with(model: jj, local: true) do |form| %>
  <% if jj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jj.errors.count, "error") %> prohibited this jj from being saved:</h2>

      <ul>
      <% jj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :header %>
    <%= form.text_field :header, id: :jj_header %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :jj_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/j_js/edit.html.erb
<h1>Editing Jj</h1>

<%= render 'form', jj: @jj %>

<%= link_to 'Show', @jj %> |
<%= link_to 'Back', jjs_path %>

app/views/j_js/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jjs</h1>

<table>
  <thead>
    <tr>
      <th>Header</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jjs.each do |jj| %>
      <tr>
        <td><%= jj.header %></td>
        <td><%= jj.body %></td>
        <td><%= link_to 'Show', jj %></td>
        <td><%= link_to 'Edit', edit_jj_path(jj) %></td>
        <td><%= link_to 'Destroy', jj, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jj', new_jj_path %>

app/views/j_js/new.html.erb
<h1>New Jj</h1>

<%= render 'form', jj: @jj %>

<%= link_to 'Back', jjs_path %>

app/views/j_js/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Header:</strong>
  <%= @jj.header %>
</p>

<p>
  <strong>Body:</strong>
  <%= @jj.body %>
</p>

<%= link_to 'Edit', edit_jj_path(@jj) %> |
<%= link_to 'Back', jjs_path %>