config/routes.rb
Rails.application.routes.draw do
  resources :david_and_naomis
  resources :cody_and_amandas
  resources :jjs
  resources :shorties
  resources :grams
  resources :tom_and_moms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shorty.rb
class Shorty < ApplicationRecord
end

app/controllers/shorties_controller.rb
class ShortiesController < ApplicationController
  before_action :set_shorty, only: [:show, :edit, :update, :destroy]

  # GET /shorties
  # GET /shorties.json
  def index
    @shorties = Shorty.all
  end

  # GET /shorties/1
  # GET /shorties/1.json
  def show
  end

  # GET /shorties/new
  def new
    @shorty = Shorty.new
  end

  # GET /shorties/1/edit
  def edit
  end

  # POST /shorties
  # POST /shorties.json
  def create
    @shorty = Shorty.new(shorty_params)

    respond_to do |format|
      if @shorty.save
        format.html { redirect_to @shorty, notice: 'Shorty was successfully created.' }
        format.json { render :show, status: :created, location: @shorty }
      else
        format.html { render :new }
        format.json { render json: @shorty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shorties/1
  # PATCH/PUT /shorties/1.json
  def update
    respond_to do |format|
      if @shorty.update(shorty_params)
        format.html { redirect_to @shorty, notice: 'Shorty was successfully updated.' }
        format.json { render :show, status: :ok, location: @shorty }
      else
        format.html { render :edit }
        format.json { render json: @shorty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shorties/1
  # DELETE /shorties/1.json
  def destroy
    @shorty.destroy
    respond_to do |format|
      format.html { redirect_to shorties_url, notice: 'Shorty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shorty
      @shorty = Shorty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shorty_params
      params.require(:shorty).permit(:header, :body)
    end
end

app/helpers/shorties_helper.rb
module ShortiesHelper
end

app/views/shorties/_form.html.erb
<%= form_with(model: shorty, local: true) do |form| %>
  <% if shorty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shorty.errors.count, "error") %> prohibited this shorty from being saved:</h2>

      <ul>
      <% shorty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :header %>
    <%= form.text_field :header, id: :shorty_header %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :shorty_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shorties/edit.html.erb
<h1>Editing Shorty</h1>

<%= render 'form', shorty: @shorty %>

<%= link_to 'Show', @shorty %> |
<%= link_to 'Back', shorties_path %>

app/views/shorties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shorties</h1>

<table>
  <thead>
    <tr>
      <th>Header</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shorties.each do |shorty| %>
      <tr>
        <td><%= shorty.header %></td>
        <td><%= shorty.body %></td>
        <td><%= link_to 'Show', shorty %></td>
        <td><%= link_to 'Edit', edit_shorty_path(shorty) %></td>
        <td><%= link_to 'Destroy', shorty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shorty', new_shorty_path %>

app/views/shorties/new.html.erb
<h1>New Shorty</h1>

<%= render 'form', shorty: @shorty %>

<%= link_to 'Back', shorties_path %>

app/views/shorties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Header:</strong>
  <%= @shorty.header %>
</p>

<p>
  <strong>Body:</strong>
  <%= @shorty.body %>
</p>

<%= link_to 'Edit', edit_shorty_path(@shorty) %> |
<%= link_to 'Back', shorties_path %>